services:
  db:
    image: mysql:8.4
    container_name: codenames-mysql
    restart: always
    environment:
      env_file: "database_info.env"
    volumes:
      - ./sqldata:/var/lib/mysql:Z
    ports:
      - "3306:3306"