---
config:
  class:
    hideEmptyMembersBox: true
  flowchart:
    nodeSpacing: 50
    rankSpacing: 75
  layout: elk

---

classDiagram
    direction TB
    App --> startingPage
    App --> SpymasterPhase
    App --> OperativePhase
    App --> OperativeHub
    App --> gameHub

    startingPage --> LeftHalfStartingPage
    startingPage --> RightHalfStartingPage
    startingPage --> Footer

  LeftHalfStartingPage --> ButtonBase

    SpymasterPhase --> GameGrid
    SpymasterPhase --> FaseLabel
    SpymasterPhase --> PageHeader
    SpymasterPhase --> InputField
    SpymasterPhase --> ArtInfo

    OperativePhase --> GameGrid
    OperativePhase --> FaseLabel
    OperativePhase --> PageHeader
    OperativePhase --> ArtInfo

    OperativeHub --> OperativeHubButton
    OperativeHub --> OperativeHubCard
    OperativeHub --> GameModeCard

    PageHeader --> HeaderLogo
    PageHeader --> HeaderButton

    HeaderLogo --> IconPalette

    GameGrid --> boardCard

    gameHub --> GameHubButton
    gameHub --> Footer

    boardCard --> LockButton
    LeftHalfStartingPage --> ArticLogo

%%modal
    LeftHalfStartingPage --> BaseModal
    LeftHalfStartingPage --> StartingPageModalContent

    OperativePhase --> TutorialButton
    OperativePhase --> BaseModal
    OperativePhase --> OperativeModalContent
    OperativePhase --> OperativeResultModalContent

    SpymasterPhase --> TutorialButton
    SpymasterPhase --> SpymasterModalContent
    SpymasterPhase --> BaseModal
    SpymasterPhase --> SpymasterResultModalContent



    namespace boardFolder {
        class boardCard {
            <<VueComponent>>
            -const clicked
%%          props
            +String id
            +String imgUrl
            +String altText
            +String color
            +String phase

%%          emits
            +emit card-clicked()
        }

        class FaseLabel {
            <<VueComponent>>
            +String fase
        }

        class GameGrid {
            <<VueComponent>>
%%          props
            +Array cards

%%          emits
            +emit card-clicked()
        }

        class InputField {
            <<VueComponent>>
%%             props
               +String label
               +String modelValue
               +String name
               +Boolean readonly
               +Boolean inputDisabled

               -buttonClick()
%%             emits
               +emit submit()
               +emit update:modelValue(value)
        }

        class LockButton {
            <<VueComponent>>
%%             props
               +String id
%%             emits
        }

        class ArtInfo {
            <<VueComponent>>
%%             props
               +String title
               +String artist
               +String medium
               +String origin
               +String style
               +String date
%%             emits
               +close()
        }
    }

    namespace headerFolder {
        class PageHeader {
            <<VueComponent>>
%%             props
               +String username
%%             emits

        }

        class HeaderButton {
            <<VueComponent>>
%%             props
               +String username
%%             emits

        }

        class HeaderLogo {
            <<VueComponent>>
%%             props
%%             emits

               +const router
        }

        class IconPalette {
            <<VueComponent>>

        }
    }

%% hubs folder
    namespace operativeHubFolder {
        class OperativeHubButton {
            <<VueComponent>>
%%              props
                +Number gameID
                -goToOperativePhase()
%%              emits


        }

        class OperativeHubCard {
            <<VueComponent>>
%%             props

%%             emits

        }

        class GameModeCard {
            <<VueComponent>>
%%             props
%%             emits

        }

        class OperativeHub {
            <<VueComponent>>
%%             props
%%             emits

        }
    }

    namespace gameHubFolder {
        class GameHubButton {
            <<VueComponent>>
%%          props
            +String eyeBrow
            +String phase
            +String subText
            +String imgUrl
            +String altText
%%           emmits
            +button-click()
        }

        class gameHub {
            <<VueComponent>>
            -goToSpyPhase()
            -goToOperativePhase()
        }
    }

    namespace footer {
        class Footer {
            <<VueComponent>>
            -year()

        }
    }
%% modal
    namespace modalContentFolder {
        class OperativeModalContent {
            <<VueComponent>>
        }

        class OperativeResultModalContent {
            <<VueComponent>>
               -const score
%%             props
               +Number score
               +Number amount
               +Number selectedAmount
               +Number correctAmount
               +push(page)
               +go()
        }

        class SpymasterModalContent {
            <<VueComponent>>
        }

        class SpymasterResultModalContent {
            <<VueComponent>>
           +push(page)
               +go()
        }

        class StartingPageModalContent {
            <<VueComponent>>
        }
    }

    namespace modalLinks {
        class BaseModal {
            <<VueComponent>>
               -const visible
               -show()
               -hide()
        }

        class ButtonBase {
            <<VueComponent>>
        }

        class TutorialButton {
            <<VueComponent>>
               +const modal
%%             props
%%             emits

        }
    }
    namespace  pagesFolder {
        class SpymasterPhase {
            <<VueComponent>>
%%             props
%%             emits

        }

        class OperativePhase {
            <<VueComponent>>
%%             props
%%             emits

        }
    }

%% is in the pagesfolder
        namespace startingPageFolder {
            class startingPage {
            <<VueComponent>>
%%             props
%%             emits

            }

            class LeftHalfStartingPage {
            <<VueComponent>>
%%             props
%%             emits

            }

            class RightHalfStartingPage {
            <<VueComponent>>
%%             props
%%             emits

            }

            class ArticLogo {
            <<VueComponent>>
%%             props
%%             emits

            }
        }

%% vue default classes
    class App {
            <<VueComponent>>
%%             props
%%             emits

    }
