spring.application.name=  ${NAME_BACKEND}
# database connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_USER_PASSWORD}
server.port=${PORT_BACKEND}
# allows springboot to write database
spring.jpa.hibernate.ddl-auto=create
# uses data.sql for initialization
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true