spring.application.name=  ${NAME_BACKEND}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_USER_PASSWORD}
server.port=${PORT_BACKEND}
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never